### ISSUE TITLE
Fee reimbursement for trade oxGWbhP

### ISSUE THREAD

**Issue by asus23prime** [bisq-network/support#1540] opened 2024-01-08 16:39 UTC
![Screenshot 2024-01-08 162610 b](https://github.com/bisq-network/support/assets/155997612/05dd78d4-52bf-419e-9650-4358bf1754a0)

Maker fee transaction ID - ba6133f90bb8f15c340ecc4c888e8aea9c6946af2b8e63b90c2ceeecc4f1c245

Taker fee transaction ID - 990dc4de5bb8493d11b52c56e004502744015ee2c5a30a013946df9a35cc1629

Deposit transaction ID - 4e546139bb2d2464c1843dd37ca6f3151778f89fd64accfa00e1133693633f10

Delayed payout transaction ID - 8f0cf11f2605c040780f41dbbcb44532befd8c8f86c6039a432a451259a22c81

Bisq version: 1.9.14

BTC address for reimbursement:  3EKTXZ5BdBVMQ37pyTe6k8kU1xBw6nRU7S

**Comment by pazza83** [comment] 2024-01-08 19:53
@asus23prime 

You lost a total of **0.00016998 BTC** on this trade. This is from your trade and miner fees.

Thanks for providing your logs that showed it was caused by this issue https://github.com/bisq-network/bisq/issues/6948

@leo816 will reimburse you to the bitcoin address provided, will be in about 1 months time.

You did not lost your trade amount or deposit as this was used in a subsequent trade.

**Comment by leo816** [comment] 2024-01-29 09:06
Payout made with #1557

**Closed as completed by leo816** 2024-01-29 09:06 UTC
