### ISSUE TITLE
Fee reimbursement for trade zyjzoe5

### ISSUE THREAD

**Issue by ghubstan** [bisq-network/support#976] opened 2021-08-02 13:49 UTC
Dispute Details View (mediator pazza never found support ticket on his UI)

![zyjzoe5-dispute-details](https://user-images.githubusercontent.com/36207203/127871289-a7a63764-ad32-4220-878a-874104f5d889.png)

Failed Trade Details (peer would not communicate with mediator or myself on Bisq chat or keybase)
![zyjzoe5-failed-trade-details](https://user-images.githubusercontent.com/36207203/127871298-bd566eef-9a86-45f5-b24f-9ad3f5817e1f.png)

Maker:  .......... `f92ca78ae9f9385b499ca48081f0fa0b25e3d3bbb0ae572cf3cfd133ad38f85d`
Taker: ...........   `f4f616634526068951761fb95b699dda8ee9e2bbc3a965fe2c3ee94cec9bf78b`
Deposit: ..........   `c8d0a58163e7df951a9762f131ad27b8b1a304db066d88a770c7a718f7134a4f`

Bisq version:  1.7.1 and v.1.7.2

BTC address for reimbursement:   `1HUP4WvE9MBouPSaTviKAUUnr9Ze3EVPbe`

Other notes:

TRADE:  zyjzoe5-52376056-1bb2-471b-bac5-e33a2af3a47e-170 

Problem:  I took an offer from a maker that never paid a maker fee.  My ‎0.04604780 BTC taker fee is locked up.

I was unable to create support ticket and chat with mediator pazza on Bisq UI (he never saw support ticket).
Related to https://github.com/bisq-network/bisq/issues/5642

I was unable to communicate with maker via Bisq chat due to chat bugs and unwillingness of other side to communicate on keybase.

Other side was unwilling to chat with mediator @pazza on keybase.

Maker fee TX ID		`f92ca78ae9f9385b499ca48081f0fa0b25e3d3bbb0ae572cf3cfd133ad38f85d`  NEVER REACHED MEMPOOL
Taker fee TX ID		`f4f616634526068951761fb95b699dda8ee9e2bbc3a965fe2c3ee94cec9bf78b`  CONFIRMED
Deposit TX ID		`c8d0a58163e7df951a9762f131ad27b8b1a304db066d88a770c7a718f7134a4f`  NEVER REACHED MEMPOOL

https://mempool.space/tx/f92ca78ae9f9385b499ca48081f0fa0b25e3d3bbb0ae572cf3cfd133ad38f85d
https://mempool.space/tx/f4f616634526068951761fb95b699dda8ee9e2bbc3a965fe2c3ee94cec9bf78b
https://mempool.space/tx/c8d0a58163e7df951a9762f131ad27b8b1a304db066d88a770c7a718f7134a4f

Peer:  6ld2bdl5muonnzeum5vph4fknu44avuhrz6qzwsldrekmxpwdawwpcad.onion:9999

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment] 2021-08-03 23:36
Hi @ghubstan thanks for creating this issue.

I can confirm that I did not have a ticket created in my mediator account for `zyjzoe5`

I sent over my logs to @jmacxx and it looks like at the same time you raised the ticket my Bisq instance was forcibly closed as a result of the java heap space error.

I was therefore unable to communicate with either trade party in my Bisq instance.

You reached out on Keybase but the BTC Buyer did not.

Looking at your [taker fee](https://mempool.space/tx/f4f616634526068951761fb95b699dda8ee9e2bbc3a965fe2c3ee94cec9bf78b) it appears that you paid the fee in [BSQ](https://mempool.space/bisq/tx/f4f616634526068951761fb95b699dda8ee9e2bbc3a965fe2c3ee94cec9bf78b). 

As there was no [maker fee](f92ca78ae9f9385b499ca48081f0fa0b25e3d3bbb0ae572cf3cfd133ad38f85d) the trade failed and no deposit tx id was created.

Therefore you have lost in this trade: 2,390 sats plus the trade fee of 3.21 BSQ.

I think the 'locked' 0.04604780 BTC is more likely to be a GUI error.

I will message you on Keybase to see if this can be confirmed ,or not, and report back.

**Comment by pazza83** [comment] 2021-08-09 21:01
Just to confirm that following chat with @ghubstan on Keybase. The 'locked' 0.04604780 BTC was used to fund another trade and is likely a GUI error.

As the trade failed compensation should take into account your mining fees of 2,390 sats plus your trade fee of 3.21 BSQ.

I will leave this open in case @ghubstan wishes to add any more comments and for @leo816 to close / action as necessary.

**Comment by ghubstan** [comment] 2021-08-11 14:13
I have lost 2,390 sats plus the trade fee of 3.21 BSQ in this failed trade.  Several conversations with @pazza83 (keybase) and my tx history tell me I may have not lost what my GUI says are locked up 0.04604780 BTC.  When I have time, I will run the API over this data dir to see if the problem is lower down than the GUI layer, down in `bisq.core` or the `bitcoinj` library.  

I don't want to lose open offers by moving funds from this corrupted(?) data dir for a new one, to make this problem go away and close the issue.  But @leo816 will do as he sees fit -- to follow the protocol in this situation.  If I discover something interesting after more troubleshooting on my end, I can re-open or reference this issue in a new one.

**Comment by pazza83** [comment] 2021-08-29 23:18
Hi @ghubstan 

This trade has now been reimbursed.

Tx id: https://mempool.space/tx/1beb4847496943bae86d1032d364af6936cfe217f49dd18d9964bf6aa2f95ae2

**Closed by pazza83** 2021-08-29 23:18 UTC
