### ISSUE TITLE
Fee reimbursement for trade BWYNMFEE

### ISSUE THREAD

**Issue by spx4000** [bisq-network/support#521] opened 2020-10-31 07:23 UTC
![image](https://user-images.githubusercontent.com/64005249/97773613-63338d80-1b62-11eb-95ae-b2c4e568660e.png)

Maker:  cf4f4b09f2a78aaf49b52d9b2211f5b71d9b1cc57e9aee9f0f7c7177b03f113a
Taker:  a5db50e4fab6f95227d025ff5007ebdffd48484450570fcc70b86b1ba6648a33
Deposit:  8e688b734777b439642c4825fa6eed45c5723446eddfd1826e2c4c2a76b50606

Bisq version: 1.4.2

Other notes:
Total: 1057.83 BSQ
Payment: d0b868c9800aab5a9abb2a63c83d387ba2749af9918a6abb5547d20668e8fa7a

Reimbursement Amount: 0.09 BTC
Reimbursement Funds: 2a1ff7756040d8603f7b4741f11a0f31cb2a88085bfde5f0273f1ccd9c92d99b
Reimbursement Rate: 0.00005672 BTC/BSQ
Reimbursement BSQ: 1586.74

ID: BWYNMFEE-e266ed86-3c28-4b03-8ef5-6d584fefe73c-137
Price: 0.00005672 BTC/BSQ
Amount: 0.06 BTC
Deposit: Buyer 0.015 BTC / Seller 0.015 BTC

I made BSQ payment on time, and no response from either seller or mediator!! I want reimbursement for this 0.09 BTC.
@wiz @leo816 @bisq_knight

**Comment by wiz** [comment] 2020-10-31 08:17
who is your mediator for this trade? I don't have a ticket with that ID

**Comment by spx4000** [comment] 2020-10-31 08:23
Mediator is: apbp7ubuyezav4hy.onion:9999

**Comment by Bisq-knight** [comment] 2020-10-31 08:59
I've received this case on Oct 21, and replied the same day. I believe the trader(buyer) is confusing mediator not replying with Refund Agent not replying as the mediation was issued on the 27th (as soon as he provided the BSQ transaction id and I was able to verify it) and on the 30th of October the delayed payout transaction was published (the tx is still in the mempool waiting to be confirmed). 

> Reimbursement Funds: 2a1ff7756040d8603f7b4741f11a0f31cb2a88085bfde5f0273f1ccd9c92d99b

Regardless, as the full payout is on its way to the donation address, upon confirmation and considering the trade amount is still below the maximum amount the Refund Agent can handle, we should close this issue as a reimbursement request and have the trader talk to the Refund Agent for his payout instead. 

@spx4000 the main advantages of you going through the normal arbitration route are mainly: 
* faster (you don't need to wait for a DAO cycle to send the proposal, vote and get results)
* you get your part in Bitcoin directly

I believe he probably didn't hear from the Refund Agent yet as the transaction is not confirmed due to the congestion in the mempool

**Comment by wiz** [comment] 2020-10-31 09:41
This is a DAO reimbursement request for trade funds donated to Bisq. For the DAO to vote on it, we need to know the following:

1) The mediator @Bisq-knight needs to verify that the github user making this claim is actually the trader in the claim
2) The arbitrator @refundagent needs to verify the trade was not already reimbursed from the normal arbitration process, i.e. no double payout.

This should be the same process for all DAO reimbursement requests.

**Comment by RefundAgent** [comment] 2020-11-01 11:37
The trade BWYNMFEE has not been paid out by the Refund Agent. It has in fact not arrived, possibly due to mempool congestion.

**Comment by wiz** [comment] 2020-11-02 00:22
The funds were donated here and it is confirmed https://mempool.space/tx/2a1ff7756040d8603f7b4741f11a0f31cb2a88085bfde5f0273f1ccd9c92d99b

**Comment by Bisq-knight** [comment] 2020-11-02 17:41
@spx4000 I'm still waiting on your message in bisq confirming that you are who you say you are. Please open the app and reply there

**Comment by chimp1984** [comment] 2020-11-02 17:42
Please use also the signed message and mediators/refund agent need to verify the message. I fear the request was too late for that cycle. If it gets rejected just re-apply next cycle with all the required information.

**Comment by wiz** [comment] 2020-11-03 10:08
Both the mediator and refund agent confirmed the claim was valid, and the payout TX was confirmed before the voting cycle began, so all the requirements were met in time.

**Comment by ripcurlx** [comment] 2020-11-04 08:21
@spx4000 Could you please provide your `Proposal transaction id` so everyone can verify that the CR in DAO is actually made by you.

**Comment by spx4000** [comment] 2020-11-04 10:54
https://mempool.space/bisq/tx/16545ae9301d062d6344d1622f5b3e74f3eaabafba03624d7507f844a3ef8ba6

let me know if you need more

**Comment by Bisq-knight** [comment] 2020-11-05 16:41
Confirmed that @spx4000  is who he says he is

**Comment by RefundAgent** [comment] 2020-11-08 11:27
The trade BWYNMFEE has now arrived but I will not pay it out since the DAO handles it now.

**Comment by chimp1984** [comment] 2020-11-08 16:36
The request got rejected because one voter rejected with 90k BSQ and only one other accepted with 59k BSQ. No other voter voted on it. Such cases should signal the DAO stakeholder to improve their due dilligence. Why one has rejected if the people involved with the case (mediators) have signalled that this case is valid? Why nobody else voted on it? At least the mediators and refund agent should take care about cases in their domain, like devs should take car3e of their domain.

If there is a strong reason why it was rejected please post it here. 

@spx4000 I fear you need to re-do your request at the next cycle. Please understand that the DAO is young and still in a learning process...

**Comment by spx4000** [comment] 2020-11-12 10:13
@chimp1984 
Yeah, disappointing but I understand and I will refile the reimbursement request through the DAO in this current cycle and wait the 30ish days.

There is no denying that it was near the end of the cycle, and verifications were required, but personally I blame Bisq-Knight's slowness to respond at each stage of the ticket.  For example: this comment from him suggests that he had already sent me a message when in reality he sent me a message in the Bisq app 8 hours after this Github comment.

> @spx4000 I'm still waiting on your message in bisq confirming that you are who you say you are. Please open the app and reply there

I will be happy when this is finally resolved.  Thanks.

**Comment by ripcurlx** [comment] 2020-12-04 14:19
@spx4000 Can you please confirm that `a3eb23b8429d9f6aee5fe85ded68b0c4509ea09b8718374898f8404d92fb665e` is the correct transaction ID linked to your reimbursement request? Thanks!

**Comment by spx4000** [comment] 2020-12-09 02:20
@ripcurlx  Yes, that txid is correct. Thanks.

**Comment by spx4000** [comment] 2020-12-10 16:17
@Burningman3  I am trying to contact you via your keybase account: burningman3, I am spx4000 on Keybase, please message me if you see this.

**Comment by pazza83** [comment] 2021-08-29 23:32
Closing as reimbursed in cycle 19 as per DAO voting

**Closed by pazza83** 2021-08-29 23:32 UTC
