### ISSUE TITLE
offers are disabling themselves randomly

### ISSUE THREAD

**Issue by pitachef** [bisq-network/support#1135] opened 2022-08-16 10:07 UTC
Description:

My buy and sell offers are disabling themselves randomly. 
when the orders are deactivated this message appears in the terminal:

"ago.-16 13:02:29.640 [JavaFX Application Thread] INFO  b.c.p.mempool.TxValidator: Maker tx validation : SUCCESS 
ago.-16 13:03:03.158 [JavaFX Application Thread] INFO  b.d.c.c.control.PopOver: hide:200.0 ms 
ago.-16 13:03:23.925 [JavaFX Application Thread] INFO  bisq.common.util.Profiler: Total memory: 756 MB; Used memory: 723,55 MB; Free memory: 32,45 MB; Max memory: 2 GB; No. of threads: 89 
ago.-16 13:03:30.802 [JavaFX Application Thread] INFO  b.c.o.b.TriggerPriceService: Deactivating open offer fblmlu due to mempool validation 
ago.-16 13:03:30.804 [JavaFX Application Thread] INFO  b.c.o.b.TriggerPriceService: Deactivating open offer HCOML due to mempool validation 
ago.-16 13:03:47.213 [JavaFX Application Thread] INFO  b.n.p2p.peers.PeerManager: Num of latestLivePeers=17 
a"

...
...
...

"ago.-16 11:53:54.306 [JavaFX Application Thread] ERROR b.c.p.mempool.TxValidator: The apparent BSQ fee burnt seems ridiculously high (100003) compared to expected (4) 
ago.-16 11:53:54.306 [JavaFX Application Thread] ERROR b.c.p.mempool.TxValidator: Could not obtain the burnt BSQ amount, trade will be flagged for manual review. 
ago.-16 11:53:54.310 [JavaFX Application Thread] WARN  b.c.p.mempool.TxValidator: Fee does not match fee from filter. Fee from filter=1278. Expected fee: 0,04 BSQ, actual fee paid: 0,00 BSQ 
ago.-16 11:53:54.310 [JavaFX Application Thread] INFO  b.c.p.mempool.TxValidator: Maker tx validation : FAIL "
...
...
...
"[JavaFX Application Thread] INFO  b.c.p.mempool.TxValidator: Maker tx validation : FAIL "
" [JavaFX Application Thread] INFO  b.c.o.b.TriggerPriceService: Deactivating open offer fblmlu due to mempool validation "

 
Currently, all of my offers are switching themselves from on to off.
I can't use bisq anymore because of this problem.
None of my offers remain active for more than a minute

After I rebuild DAO STATE  from recources this error started to happen only with some orders, they are deactivated for no reason and others are still active

Questions:
1 - Is this a known bug/issue?
2 - What could be the root cause?
3 - What do I need to do to stop this from happening (as I do want all my offers to be active)?

started_at_UTC:
<_2022-08-13

github-issue:
issue #948

Bisq version:
1.9.4

Device or machine:
mac osx high sierra 10.13.6

thanks for your attention

**Comment by jmacxx** [comment] 2022-08-16 21:18
Thanks for raising this issue @pitachef .  It is caused by a DAO parameter update that happened yesterday.  We're working to get it resolved urgently ASAP.  Will update here soon when it has been addressed.

**Comment by pitachef** [comment] 2022-08-16 23:12
> Thanks for raising this issue @pitachef . It is caused by a DAO parameter update that happened yesterday. We're working to get it resolved urgently ASAP. Will update here soon when it has been addressed.

Thank you for your attention. I will be waiting for the resolution of this problem, thank you

**Comment by pitachef** [comment] 2022-08-17 09:32
> Thanks for raising this issue @pitachef . It is caused by a DAO parameter update that happened yesterday. We're working to get it resolved urgently ASAP. Will update here soon when it has been addressed.

PROBLEM UPDATE:

After resync DAO from "REBUILD DAO STATE FROM RESOURCES", some offers are deactivated right after the DAO sync is completed.
Just below I put the code that appears in the terminal right after the end of the synchronization and shows the deactivations of the offers:

"
...
ago.-17 10:16:15.056 [JavaFX Application Thread] INFO  b.core.offer.OpenOfferManager: OfferAvailabilityResponse arrived at peer: offerId=HCOML-fc4c19fd-937e-4017-97b8-776788942a5f-194; uid=7f046ba1-d816-4e16-a041-6f789455f096 
ago.-17 10:16:15.107 [JavaFX Application Thread] INFO  b.core.offer.OpenOfferManager: AckMessage for OfferAvailabilityRequest arrived at takersNodeAddress a5hc57fl4zy3m3t2n3akutasaqhyxpmursw26bw2codjtmgb66m5uvyd.onion:9999. offerId=HCOML-fc4c19fd-937e-4017-97b8-776788942a5f-194, sourceUid=b4b6bce9-fc0d-46a3-9f78-8ad0eedfc63e 
ago.-17 10:16:15.957 [JavaFX Application Thread] INFO  b.core.offer.OpenOfferManager: Received AckMessage for OfferAvailabilityResponse with offerId HCOML-fc4c19fd-937e-4017-97b8-776788942a5f-194 and uid 7f046ba1-d816-4e16-a041-6f789455f096 
** @ago.-17 10:16:21.994 [JavaFX Application Thread] INFO  b.c.o.b.TriggerPriceService: Deactivating open offer fblmlu due to mempool validation 
ago.-17 10:16:22.000 [JavaFX Application Thread] INFO  b.c.o.b.TriggerPriceService: Deactivating open offer HCOML due to mempool validation** 
ago. 17, 2022 10:16:39 DA MANHÃ org.apache.http.impl.execchain.RetryExec execute
....
....
...."

**Comment by jmacxx** [comment] 2022-08-17 13:02
The issue has been fixed now, your offers should no longer be deactivated.  Try restarting Bisq if the problem persists.

**Comment by pitachef** [comment] 2022-08-17 14:21
> The issue has been fixed now, your offers should no longer be deactivated. Try restarting Bisq if the problem persists.

thanks very much !! theproblem isfixed now !!!

**Closed** 2022-08-17 14:21 UTC
