### ISSUE TITLE
Reimbursement request for trade MZEFILM

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/support#500] opened 2020-09-20 05:46 UTC
![NKgCt1t](https://user-images.githubusercontent.com/45833017/93695180-45f7b200-fb14-11ea-93af-8612f335a520.png)

Maker:  6bf5336a1de66b97065403d258881d16b9f1ba109b6c5590056363b150fd861e
Taker: e4dc8ee45a145f90995a436eecca5b98f1763f0c290af12294374964d860b03d
Deposit: a2df24b89a4ec7e3244d09c914a382f84511e032639e36b4e37a819904aabe79

TradeID: MZEFILM
Time/Date: 25 aug 2020, 17:29
Payout txid: 90a378116186789b458606d13fc41b110de008040a8cad90c0d14003c05174c0
Trade amount: 2.00 BTC
Security deposit (buyer/seller): 0.42191307 BTC / 0.42191307 BTC
Mediator: @Bisq-knight [bisq_knight (apbp7ubuyezav4hy)]
Mediator secret: krt56 

Bisq version: 1.3.8

I am the BTC buyer as taker. The trade partner is unresponsive. I did make the XMR payment in full within the trade time window. Payout was sent to Bisq donation address. The suggested mediator payout was: BTC buyer: 2.42191307 BTC / BTC seller: 0.42191307 BTC

![xKYjv9S](https://user-images.githubusercontent.com/45833017/93695732-59efe380-fb15-11ea-9aea-0cda4be190ff.png)

Additional information:
The mediator proposed a 'normal' payout where each party gets their deposit back and the trade amount goes to the BTC buyer (me). I obviously disagree with this as it is an instant trade and the trade partner has become unresponsive within any reasonable amount of time (it's been almost a month).
I have pointed out the tendency of mediators to just return deposits to both parties even if people completely ignoring protocol for no apparent reason or communication. This way, the deposit gives zero incentive for people to handle trades properly.

Request:
I like to request reimbursement for the full amount,
Trade amount + own deposit + forfeited deposit of trade partner;
2.84382614 BTC

Currently with 30 day avg this would be 50217.66 BSQ at a price of 0.00005663 BTC/BSQ (2020-09-22)

Bisq Proposal ID: 2c3e0375f5478791ff8d4744049db497e69601aa60ca320abdd1087d83a79733

**Comment by wiz** [comment] 2020-09-20 08:36
@invertedbobb who was your mediator for this trade? please tag them as they will need to confirm the details of the case... and of course I don't know all the details, but 0.42 BTC is about $5000 which sounds way too much for just a delay compensation, this wasn't an intentional fraud or chargeback, you just had to wait a while, so I would suggest 0.14 BTC in this case which is about 1/3 of the other guy's security deposit, and 1/3 back to him if he wants to claim it, and the DAO keeps the last 1/3.

**Comment by chimp1984** [comment] 2020-09-20 16:35
> I have pointed out the tendency of mediators to just return deposits to both parties even if people completely ignoring protocol for no apparent reason or communication. This way, the deposit gives zero incentive for people to handle trades properly.

I agree that is not the correct strategy.

**Comment by chimp1984** [comment] 2020-09-20 16:45
I can confirm the validity of the deposit and payout tx:
https://blockstream.info/address/3KUWY4YpHanPRnXMjwgY33NgdbayExNy4b

@Bisq-knight Can you confirm the data posted?

**Comment by wiz** [comment] 2020-09-21 12:13
For the record, this is an example of a Mediator's suggested payout being challenged by a trader, and using the DAO reimbursement process as the "Supreme Court"

**Comment by chimp1984** [comment] 2020-09-21 17:51
It also shows that the quality of dispute resolution is not as it should be. The summary notes don't give any valueable information to judge. We need further information from @Bisq-knight about the reasons why he decided to refund the deposit ot the not responding peer, which should be penalized with not getting any refund.

**Comment by chimp1984** [comment] 2020-09-21 20:37
@invertedbobb Can you PM me on keybase the XMR tx key so I can verify the XMR payment?

**Comment by chimp1984** [comment] 2020-09-21 22:01
I can confirm the XMR was sent by the tx key he provided me.

**Comment by Bisq-knight** [comment] 2020-09-24 11:59
In this trade I got the following:
Both parties replied my messages, here's a summary based on the timestamps in my bisq client

* 25th of Aug - trade started 
* 30th of Aug - Buyer says Seller is not responding (did not provide proof of payment). I suggested to wait
* 4th of Sept - The Seller said this trade went into Failed on his end and didn't answer anything else
* 5th of Sept - The delayed payout tx was [published](https://blockstream.info/tx/90a378116186789b458606d13fc41b110de008040a8cad90c0d14003c05174c0) (I don't know by whom, as the mediation had not been issued by then) 
* 7th of Sept - Seller asks me where is his part of the trade is


So I don't think this is total unresponsiveness, but it was a delay on the Seller side as he started answering but there was not enough time to arrive at a solution. I then, after the delayed payout tx was published, issued a simple amicable mediation as it was already out of my hands and wanted to close the case.

I side with Wiz that the Buyer does deserve compensation, as he put this case up for us to discuss while the Seller simply didn't show up after the messages above. But I don't think his compensation should be total amount. We don't have precedent of the DAO holding funds in case if a trader shows up in a month but this case shows us that:
* Unresponsive traders can happen in all stages of the trade: during the trade, during mediation, during arbitration -> what should be our policy on that
* How, exactly, should traders be compensated for taking the time, effort and fx risk of going through the reimbursement process to get their share in BSQ?

**Comment by invertedbobb** [comment] 2020-09-25 16:21
@Bisq-knight You have not communicated these responses from the trade partner to me.
Your last mediation message to me was on 31 august telling me he has 10 days to respond. I acknowledged to wait that period.
After the time expired i published the delayed payouttx.

I would argue it is utter nonsense that his trade was failed, as he communicated with me in the chat of this trade initially about TradeID 49320. There is no chat option when the trade has failed. (I can provide screenshots if needed)

If he had become responsive, why was i not informed? He didn't respond to me even after repeated messages.
If i had known he was 'back', i hadn't pushed the delayed payouttx and it could have been resolved through mediation.
Anyway, it is what it is now.

Unresponsive traders are not a problem as long as trade protocol is followed.
As i understand it, the security deposit is intended to 'secure'  exactly that, people adhering to the trade protocol. And when you don't do that, and worse, fail to communicate to find a solution, in my opinion you forfeit your security deposit to the trade partner.
If this is not the intention of the security deposit, then what is? If not the full amount should be forfeited, then how much? Why do we have the option to select it as we please? I set a higher security deposit on almost all my trades specifically to increase incentive to handle the trade properly. If that serves no use, then why have that option in the first place?

**Comment by Bisq-knight** [comment] 2020-09-26 14:37
yes, @invertedbobb let's keep the two things separate.

1) **your compensation** -> I read from [here](https://github.com/bisq-network/support/issues/502#issuecomment-699031864) that you agree with what we proposed. Good, we can close this part of the topic then. 👍

2) **precedence and what we should do about cases like this**. Like I said in the other message, @invertedbobb is welcome to add his suggestions here and it should not be specific to this case, but a general approach to things. Specifically how do we solve:
* How long from the delayed payout tx is published (and received by the DAO donation address) until we approve (and issue BSQ) a reimbursement by the DAO? how long should that period be? - keep in mind that it needs to take into account at least some time for a trader to contest a reimbursement request on github.
 * How do we account for and mitigate risks taken by the DAO? in this case, there is a risk being taken by the DAO related to the trade that doesn't have a payout tx (thus has +2 BTC locked) and is the case for one of @invertedbobb's transactions. The DAO is trusting that @invertedbobb is 1) not  trading with himself and assuming that 2) the other trader will not be back to sign the mediation suggestion thus signing the transaction. If either of these cases materialize, the DAO issued BSQ that was not accounted for by the donations it has, i.e. all Bisq contributors pay that price with BSQ inflation.

**Comment by sqrrm** [comment] 2020-09-29 16:41
I basically agree with @invertedbobb here. There was a protocol violation, it should be punished. Giving some or all of the sellers deposit to the buyer seems ok, main point is that the seller should not get anything back for a case where they violated the protocol and the case was taken to the DAO.

The BSQ rate is not in line with the monthly rate we use for compensation requests, perhaps that's not right, but I think it's important to get this case resolved. Better guidelines for reimbursement requests going forward would be good.

**Comment by sqrrm** [comment] 2020-09-29 16:48
@invertedbobb Could you post the proposal transaction ID as well.

**Comment by invertedbobb** [comment] 2020-09-29 20:20
Added Bisq Proposal ID in OP.

**Comment by chimp1984** [comment] 2020-09-30 05:22
>     * Unresponsive traders can happen in all stages of the trade: during the trade, during mediation, during arbitration -> what should be our policy on that

In old arbitration system there was a clear rule that after 2 days (not 100% sure anymore what was the max period) not replying the not responding peer has lost the case and deposit goes to 100% to peer. We have to enforce those rules more strongly. If there are UX problems or bugs causing that we need to fix it. But it seems that is not the major issue here.

**Comment by Bisq-knight** [comment] 2020-11-02 17:58
Cycle 17
Approved

**Closed by Bisq-knight** 2020-11-02 17:58 UTC
