### ISSUE TITLE
Reimbursement for mGIFEmwE - missing payout

### ISSUE THREAD

**Issue by felipesocha** [bisq-network/support#1457] opened 2023-08-14 22:03 UTC
![photo_5102896712653057367_y](https://github.com/bisq-network/support/assets/107418776/711d0f47-25a5-4625-96fe-83a441d30662)

Reimbursement for trade mGIFEmwE-c52d401c-3f81-4f4b-bd8a-1b16445bb772-1912 

I am BTC buyer as maker
Trade amount and asset: 0.04 BTC for 5738 BRL
Deposit amount: 0.0060 BTC

Maker:  c8ce5240c51fa3210ff430e67acd31dc068e1b17cc0a7628347017ccc6fbb378
Taker: 3fd72ea13732e1cda0d235c6fbabcc2d1c25ad53cec3b7e662a59da4c9b87bfe
Deposit: 7d7f2426f12787eaefd8cdf1b5e371685355571c9fc0dd5ed6dd0445c080a788
Delayed payout: 1c01b6f334885a97e7a29259693b132e60a5f48babf6169050194ad594670065
BuyerMultiSigPubKeyHex: 037d5e1694f336c0701331aaa06fa96434a317d2780785c31028233b56e5641922
SellerMultiSigPubKeyHex: 036422efeb63994f6b7c338b827c47b1cf1f9b5d7f0bada9d7de8ae89928af0fd6

Reimbursement amount: 0.01 BTC / [30 day BSQ average] BSQ = [TOTAL AMOUNT] BSQ
Reason for reimbursement: BUG IN PAYOUT TRANSACTION

BTC address ownership proof:

Bisq version:

Other notes:

Goodnight. In this negotiation that started on 07/12/2023, I made the payment to the seller and he confirmed the payment, releasing the btc, however there was no transaction to the indicated address, leaving the btc at the multisig address.
As I had already concluded the negotiation and moved the ticket to the history, I was unable to open mediation or arbitration to solve the problem.

On 07/14/2023 I looked for the indicated mediator (leo816) on element to help me with the release of funds. As he was unable to contact the seller, it was not possible to make the manual payment, which is why I was instructed to wait for the movement of the btcs that were in the multisig address to then request arbitration.

On 02/08/2023, there was a movement of the btc that were locked in the multisig address ( bc1qw6kszzlkw709yzgmff0w2e3g95fqjhegalxm97ymc4ax0eanqxzsuupern ). So on 08/04/2023 I contacted Leo816 again informing the fact and he told me to contact the referee (refundagent2)

As I couldn't get in touch with him, on 08/08/2023 I got support from Suddenwhipvapor to help me with my problem. When analyzing it, he told me that it was a known bug.

So, we called the refundagent2 arbiter who informed on 08/09/2023 that the seller had contacted me and since he couldn't reach me he decided in favor of him applying a reduction that cost me 0.01 btc. The transaction that paid me the btc is this one ( b180e07d6de0956e2258a158c2efc5df0307b77ef6e417d1b3bc96ae2b2499d9 ) and I only received 0.036 btc when in fact I should have received 0.04 btc purchased + the security deposit of 0.006 btc.

As instructed by Sudden, there was nothing else that refoundagent2 could do, directing me to seek reimbursement from the DAO since on 7/17/2023 I sought a solution to my problem.

>_Ping @refund-agent2 and your mediator_
Selected mediator: leo816
Selected arbitrator (refund agent): refundagent2

**Comment by darawhelan** [comment] 2023-08-17 00:03
Ping @leo816

**Comment by leo816** [comment] 2023-08-24 09:49
@felipesocha Mediation proposal wasn't accepted by both parties therefore @refundagent is in control. Was the payout made on this one?

**Comment by felipesocha** [comment] 2023-08-24 21:17
Yes. @refundagent took over. he ended up releasing the funds through this transaction and I only received 0.036 btc as a penalty was imposed on me. Since there was a bug and it was not my intention not to release the funds, this fact is proven by the fact that I contacted the mediator to seek the release of funds at the multisig address, but this was not possible within the deadline. So I come to request that the penalty imposed on me be refunded, that is, 0.01 btc

b180e07d6de0956e2258a158c2efc5df0307b77ef6e417d1b3bc96ae2b2499d9

**Comment by pazza83** [comment] 2023-08-25 01:24
Hi @leo816 

I remember discussing this on a support call.

@felipesocha was affected by the address reuse bug: https://bisq.wiki/Trade_payout_address_reuse_issue

Therefore @felipesocha was not aware that the trade had taken place.

I think @suddenwhipvapor was supporting them. Please can @suddenwhipvapor confirm if this is the case.

I think it would also be good if @refund-agent2 could also confirm how much bitcoin @felipesocha was penalized for not responding in arbitration.

Trade ID: mGIFEmwE had 0.052 BTC pay out to the multisig and 0.046 BTC was paid out in total in arbitration.

With regards the process for compensation I think it should go to a DAO vote. 

@felipesocha I think the steps that need to happen to make this reimbursement are as follows:

1. @suddenwhipvapor confirms the issue is as described
2. @refund-agent2 confirms how much bitcoin was penalized from the BTC buyer 
3. @felipesocha signs a message for the maker payout address to prove they are the Buyer in Trade ID: mGIFEmwE 
4. @felipesocha creates a [reimbursement request](https://bisq.wiki/Making_a_reimbursement_request) that the DAO can vote on

@felipesocha apologies for all the steps needed get a refund for what was a Bisq bug. If you would like to get any support from me about any of the steps please feel free to reach out to me on Bisq's Matrix chat: https://bisq.wiki/Matrix_bisq.chat

My username there is: @pazza83:matrix.org

**Comment by suddenwhipvapor** [comment] 2023-08-25 14:21
> @suddenwhipvapor confirms the issue is as described

I can confirm one [@felipesocha:matrix.org](https://matrix.to/#/@felipesocha:matrix.org) reported exactly this story, there were other circumstances but bottomline is that he was not aware of the status of the trade, just that he didn't receive the bought btc, and he finds out about the arbitration later on

**Comment by pazza83** [comment] 2023-08-25 14:49
Thanks @suddenwhipvapor 

I have found the mediation ticket.

Ticket closed on Aug 9, 2023 11:41:07 AM
Arbitrator node address: 3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion:9999

Summary:
Trade ID: mGIFEmwE

Reason for dispute: Trader not responding
Payout suggestion: Custom payout
Trade amount: 0.04 BTC
Payout amount for BTC buyer: 0.0360 BTC
Payout amount for BTC seller: 0.01 BTC

Summary notes:
A bug required mediation, but buyer is unresponsive. Payment was sent.
Buyer receives trade amount - 10% penalty, seller receives security deposit + 10% compensation.
A security deposit is left unpaid.

-----BEGIN SIGNATURE-----
302c02145f3e907349d6aea87842d7ac08ff7897ce9efe7d021406b10d8edda24562c15f0675e07b35edd61bc67e
-----END SIGNATURE-----

So if the trade had been affected by the bug the buyer would have received 0.04 BTC trade amount plus their 0.006 BTC deposit.

So @felipesocha is correct when they say they lost out 0.01 BTC as a result of the address reuse bug

**Comment by felipesocha** [comment] 2023-08-25 15:08
Yes, it's correct. should have received the 0.04 btc purchased plus the 0.06 btc security deposit. but I received from the arbitrator only 0.36 btc

**Comment by pazza83** [comment] 2023-08-25 23:28
I have received verification that @felipesocha owns the address (bc1qlm5qnx2vr8k9xcya4ryfytsegp4xyfa6uqhgy8) for reimbursement:

Address: bc1qlm5qnx2vr8k9xcya4ryfytsegp4xyfa6uqhgy8
Message: felipesocha
Signature: IBOnUTuytc/6fFpLGBFegVHtMg0EkCIMhZ5N1h0sYUWGew54319TuF2gXr4SEhd6BJukaCzm/WOn1Rw72vlFAzg=

@refund-agent2 can you confirm that the address bc1qlm5qnx2vr8k9xcya4ryfytsegp4xyfa6uqhgy8 is the correct maker payout address for trade ID: mGIFEmwE 

Many thanks

**Comment by refund-agent2** [comment] 2023-08-28 16:05
`bc1qlm5qnx2vr8k9xcya4ryfytsegp4xyfa6uqhgy8` was used by buyer as maker for this trade. Signature was verified successfully for identity purpose only (the reimbursement will be in BSQ).

Ticket closed on Aug 9, 2023 11:41:07 AM
Arbitrator node address: 3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion:9999

Summary:
Trade ID: mGIFEmwE
Currency: BRL
Reason for dispute: Trader not responding
Payout suggestion: Custom payout
Trade amount: 0.04 BTC
Payout amount for BTC buyer: 0.0360 BTC
Payout amount for BTC seller: 0.01 BTC

Summary notes:
A bug required mediation, but buyer is unresponsive. Payment was sent.
Buyer receives trade amount - 10% penalty, seller receives security deposit + 10% compensation.
A security deposit is left unpaid.

-----BEGIN SIGNATURE-----
302c02145f3e907349d6aea87842d7ac08ff7897ce9efe7d021406b10d8edda24562c15f0675e07b35edd61bc67e
-----END SIGNATURE-----

**Comment by pazza83** [comment] 2023-08-28 22:34
Thanks, @felipesocha you will need to make a reimbursement request around mid September for this trade. Please reach out to me on Matrix near the time for support on how to do so.

I have also sent you a Matrix message to request your logs to find out more about why this trade ended up reusing a previous address.

**Comment by pazza83** [comment] 2023-09-13 17:06
Hi @felipesocha 

based on https://github.com/bisq-network/compensation/issues/1368 I think you should use the rate for reimbursement as: 0.00002665 BSQ / BTC

This would mean you should ask for 376 BSQ as reimbursement.

To do so do the following:

1. Load up Bisq
2. Go to DAO > Governance
3. Click Make Proposal
4. Select Reimbursement request
5. Enter your Github name: felipesocha
6. Enter: https://bisq.network/dao-reimbursement/1457
7. Enter 376 BSQ
8. Then click make proposal
9. The paste the transaction ID for the transaction in a comment below. You can find it in DAO > BSQ Wallet > Transactions

**Comment by felipesocha** [comment] 2023-09-13 20:17
d8b8e4c4dcf31b467e08637ac6a5a00298ab90c05acb4cbafe5c14abb0edae83

**Comment by pazza83** [comment] 2023-09-16 16:16
Hi @felipesocha thanks for submitting. I can confirm that this has been done correctly and that I am in agreement with your case for reimbursement.

The vote result will be published around 3rd October. So you will find out if your reimbursement request has been successful then.

**Comment by pazza83** [comment] 2023-10-03 19:23
Hi @felipesocha this reimbursement was accepted in DAO vote cycle 51.

Many thanks,

Will close this issue now

**Closed as completed by pazza83** 2023-10-03 19:23 UTC
