### ISSUE TITLE
Fee reimbursement for failed trade Deposits

### ISSUE THREAD

**Issue by Wrecktangl3** [bisq-network/support#797] opened 2021-01-27 23:38 UTC
Hello there, I have made 3 deposits for trades and these were visible and showing in my portfolio. However, now I cannot see any of these trades in my portfolio anymore and have not received the deposits back. I have lost money for placing deposits on bitcoins I potentially wanted to buy, please help me. And yes, I have tried SPV Resync, a full App restore and a Seed restore and have gotten no results. This is in fact the third time I'm raising an Issue to try and resolve this issue and it has almost been a month now that I've tried to sort out this problem. If you could please help me resolve this issue, I would be very grateful. 
Thank you.

![Dep](https://user-images.githubusercontent.com/77015544/106068433-91d8ea00-60f8-11eb-9eeb-52606667c3c2.PNG)

Bisq Version 1.5.4

**Comment by huey735** [comment] 2021-02-02 10:11
Hello. Please reach out to me on [Keybase](https://keybase.io/team/bisq) and identify yourself by this issue url. I'm huey735.

**Comment by huey735** [comment] 2021-02-02 12:05
Duplicate of https://github.com/bisq-network/support/issues/748

**Closed by huey735** 2021-02-02 12:05 UTC
