### ISSUE TITLE
Fee reimbursement for trade Deposits!!!

### ISSUE THREAD

**Issue by Wrecktangl3** [bisq-network/support#748] opened 2021-01-08 19:55 UTC
I made 3 deposits for trades and these were visible and showing in my portfolio. However, now I cannot see any of these trades in my portfolio anymore and have not received the deposits back. I have lost money for placing deposits on bitcoins I potentially wanted to buy, please help! And yes, I have tried SPV Resync.

![image](https://user-images.githubusercontent.com/77015544/104058097-1bc51f80-51eb-11eb-99fb-87876b08131b.png)

Bisq version:

1.5.4

**Comment by leo816** [comment] 2021-01-10 14:46
Please restore from seed. First do a back up and then restore over the same app directory

**Comment by Wrecktangl3** [comment] 2021-01-14 21:24
Hello @leo816,

Thank you so much for your advice. However, I have tried both a full App restore and a Seed restore and have gotten no results. Can you please provide me with further help and guidance? Thank you.

**Comment by Wrecktangl3** [comment] 2021-01-21 20:09
@leo816 Can you please help me? It's been a week since I last messaged.

**Comment by huey735** [comment] 2021-02-02 12:05
Duplicate of https://github.com/bisq-network/support/issues/748

**Closed by huey735** 2021-02-02 12:05 UTC
