### ISSUE TITLE
Fee reimbursement for trade lCwuO-6dccf075-121b-4b44-9747-6049e0e08fa0-115

### ISSUE THREAD

**Issue by kicco-sk** [bisq-network/support#1066] opened 2022-02-25 08:48 UTC
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

<img width="737" alt="Snímka obrazovky 2022-02-25 o 9 25 50" src="https://user-images.githubusercontent.com/48488089/155728578-dc7e7914-f6c1-4353-9c8f-c93c480b9880.png">
<img width="799" alt="Snímka obrazovky 2022-02-25 o 15 05 51" src="https://user-images.githubusercontent.com/48488089/155728864-10b41a33-25a3-4796-90ed-f12b9cf4713e.png">

<img width="1164" alt="Snímka obrazovky 2022-02-25 o 9 28 06" src="https://user-images.githubusercontent.com/48488089/155681744-eb454a5a-77e1-4044-96a2-d6e44acbfa67.png">
<img width="749" alt="Snímka obrazovky 2022-02-25 o 9 28 35" src="https://user-images.githubusercontent.com/48488089/155681761-a695a9f2-38ce-48eb-bef3-4ba3e38b0a88.png">

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

  Maker:  095e6b6a608253d530584532ab352f2c01c8454ec57b50833b68b585688368ca
  Taker: 3cbb4fcb9c2307896c837027bbdfc523e7040a49ea5a97d168e32fd0fc4553f4
  Deposit: c0858b380dfe6780439ff984dc4691f8fc8196f881e87aba8c48347038b5763b

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:  v1.8.2 
BTC address for reimbursement: bc1qypuj2vqycj0cjtdaavw8n8y3styeh4w2urc5r9

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment] 2022-03-04 23:21
Hi @kicco-sk thanks for posting.

Looks like this was a trade for 2019 when the trade protocol was different than the current one.

Maybe @jmacxx or @leo816 can confirm what reimbursement, if any, there is for this trade, and if any other info is needed.

**Comment by pazza83** [comment] 2022-03-05 00:47
Hi @kicco-sk are you able to send me a copy of the trade Detail Data?

You can send it to me on Keybase: https://keybase.io/pazza

or Matrix: @pazza83:matrix.org

**Comment by pazza83** [comment] 2022-03-13 15:02
Hi @kicco-sk thanks for providing me with the details on Keybase. Will get back to you asap.

**Comment by pazza83** [comment] 2022-03-13 17:01
Hi @kicco-sk 

I asked one of the devs to take a look at the trade for me.

They have confirmed the trade paid out correctly:
 
Taker seller (1A4PDEAoCk8YB5bcq8rHTuR673hbZzCjAe) received their security deposit of 0.005, 
Maker buyer (1GqHqcb5PrC8cYqHtvfhmjhikku2SydxfD) received 0.011 which is trade amount plus security deposit.

Therefore, there is no refund needed

**Comment by pazza83** [comment] 2022-03-16 00:11
It might be your locked funds are showing incorrectly on the GUI.

I would recommend [backing up the application data](https://bisq.wiki/Backing_up_application_data) and then doing an [SPV resync](https://bisq.wiki/Resyncing_SPV_file ) 

Let me know if that fixes the balance for you.

**Comment by leo816** [comment] 2022-03-30 15:42
payout was made here, will close this issue

**Closed by leo816** 2022-03-30 15:42 UTC
