### ISSUE TITLE
Reimbursement request for trade LMKSE38C

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/support#501] opened 2020-09-20 05:57 UTC
![wnDryFh](https://user-images.githubusercontent.com/45833017/93697218-cec31d80-fb15-11ea-956c-da7c8439da47.png)

Maker: 75f07c01dfda037c75d627f64738f2ddadfb043493017a167670ce52d0ee9232
Taker: ee28a7187d23266b1ebb18fe5bfc4b328762b06899fdb4a676aeba3e7ee869b9
Deposit: c0f9793a82a4713b5f0c4137e12d9d4688e82de71024292a07aacbc95e35af32

TradeID: LMKSE38C
Time/Date: 25 aug 2020, 17:29
Payout txid: 37af92a864d01e17da26fc106972cb0f8c4f3ed383a3b82ddc68956af483b1f4
Trade amount: 0.70 BTC
Security deposit (buyer/seller): 0.1050 BTC / 0.1050 BTC
Mediator: @Bisq-knight [bisq_knight (apbp7ubuyezav4hy)]
Mediator secret: pory67

Bisq version: 1.3.8

I am the BTC buyer as taker. The other party has become unresponsive. I did not make the payment to have funds to rebalance another failed trade with the same trade partner, as i will explain below. The suggested payout was BTC buyer: 0.8050 BTC / BTC seller: 0.1050 BTC.

![HuySXzO](https://user-images.githubusercontent.com/45833017/93697315-d5ea2b80-fb15-11ea-90e0-67177ad86d75.png)

Additional information:
Before my request makes sense i have to provide context.
The trade partner sent me a message in the chat, asking why i did not pay TradeID 49320 yet. This trade somehow failed on my end and never showed up in my 'open trades' list. I explained this to the trade partner and attempted to unfail the trade. This was not possible because i was missing the Delayed PayoutTx on my end. I asked the trade partner to share the Delayed PayoutTx with me so that we could safely unfail and continue our trade, alternatively he could open a mediation request to get TradeID 49320 canceled. After that there were no more replies to my messages, all communication stopped from their end.

Effectively the trade partner is the only one that can do anything with the funds locked in TradeID 49320, as i cannot move it to arbitration (donation address) because this is exactly the Delayed PayoutTx i'm missing and why the trade failed on my end.

When I realized did not have the Delayed PayoutTx on my end, and I had no way of unlocking funds for arbitration in case there was a conflict or the trade partner would become unresponsive, I decided to not pay This trade, TradeID LMKSE38C. Such that in an unfortunate event, there would be funds available through mediation/arbitration to compensate for the locked funds from TradeID 49320.

I have no way of getting my security deposit back with an unresponsive trade partner that has sole possession of the Delayed PayoutTx.

[Details on the failed trade: TradeID 49320](https://github.com/bisq-network/support/issues/502)

Request:
To get back my security deposits and part of compensation, I'm requesting a rebalancing of these two trades ( [49320](https://github.com/bisq-network/support/issues/502) + [LMKSE38C](https://github.com/bisq-network/support/issues/501) with the funds available , which is 0.91 BTC.  

Currently with 30 day avg this would be 16069.22 BSQ at a price of 0.00005663 BTC/BSQ (2020-09-22)

Further details and merged proposal [HERE](https://github.com/bisq-network/support/issues/502).

I understand the situation can be confusing, please inquire if things are unclear.

**Comment by wiz** [comment] 2020-09-20 08:51
Who is your mediator for this trade? Tag them so they can confirm the details of your claim.

Strictly speaking, if you did not make the payment, you are the defaulting party for this "option trade", but I understand the reasons for wanting to cancel the trade due to the seller going unresponsive and having other trades fall into mediation. If I were the mediator on this trade I would merely suggest to cancel and each party receive their respective security deposits back, I don't think you can claim theirs if you didn't make the payment.

**Comment by invertedbobb** [comment] 2020-09-20 14:56
@wiz I didn't default. The trade partner stopped responding and this made me cautious to pay.
Paying would have resulted in the full deposit of [TradeID 49320](https://github.com/bisq-network/support/issues/502) being lost if trade partner never decides to close these trades, which has happened repeatedly in the past to me and others as you're aware. Not paying this small trade was merely intended to have funds available to the Bisq donation address to compensate for the funds locked in 49320.

**Comment by chimp1984** [comment] 2020-09-20 16:49
@invertedbobb Who was the mediator?

**Comment by chimp1984** [comment] 2020-09-20 16:52
I can confirm the validity of deposit tx to payout tx:
https://blockstream.info/address/32EDijv5QXwTDgZdVMZ6iYNqeucPKBYBPW

@Bisq-knight Can you confirm the posted data? Why did you give the not responding peer his sec. deposit back?

**Comment by invertedbobb** [comment] 2020-09-24 00:10
Further details and merge proposal [HERE](https://github.com/bisq-network/support/issues/502).

**Comment by wiz** [comment] 2020-09-24 07:04
@Bisq-knight can you please respond to this case?

**Comment by Bisq-knight** [comment] 2020-09-24 17:57
This trade followed the same pattern as [MZEFILM](https://github.com/bisq-network/support/issues/500#). The mediation suggestion was submitted AFTER the delayed payout tx was published and confirmed.

Here's the timeline (it resembles a lot the other one)
- 25th of Aug - trade started
- 31st of Aug - Mediation started - I contacted both asking for their explanations
- 30th of Aug (I think timestamps are messed probably due to settings of each trader) - Buyer contacted saying that he didn't pay because Seller hasn't answered in 5 days. I told him to hold on the payment until the other trader replies (as it is not uncommon for Monero traders to lock themselves out of bisq due to over-optimized opsec)
- Sep 1st - Buyer said he'd wait.
- Sep 4th - Seller shows up and says "his coins were sent, the trade is missing and he didn't get his coins"
- Sept 5th - Delayed Payout tx is published 
- Sep 7th - Seller contacts me with: "?"
- Sep 8th - I issue the mediation suggestion for the sake of closing the case, which has no effect since the trade already went to arbitration

In light of this trade and the other trade we have that the locktime was too short for both traders to discuss and agree on a payout. In that sense I would suggest that the Buyer (@invertedbobb ) does get compensated for it with the Seller's deposits. @invertedbobb kept his part of the trade protocol in being responsive, he didn't in not making the payment, but that is a consequence of the Seller not keeping his end of the trade protocol.

I would vouch for @invertedbobb getting the amount we're discussing on the other issue ([initial suggestion by @chimp1984](https://github.com/bisq-network/support/issues/502#issuecomment-696376150)) in the other issue and the remainder is a big question mark:
* Does the DAO get to keep it and use it to pay it's dues(i.e. the April victims)? since there is no claim (at least up until what we know today, I would suggest that)
* Does the DAO keep it for a period of time for the other trader to show up and claim his share of the trade? - this would open a very weird precedent and a whole series of potential problems (i.e. if he shows up, what's the BSQ rate that he deserves?)

I tend to think of the first option being interesting for the DAO, but that creates a malicious incentive and precedence for mediators and refund agents in the future to deliberately mismanage cases in detriment of traders and in benefit of the DAO.

To me it sounds like the second option of what to do with the remainder is the right thing to do as long as we agree on a few parameters.

But let's discuss, we need to settle these two decisions:
1. How much should @invertedbobb get out of the total - given the overview
2. what to do with with remainder

**Comment by invertedbobb** [comment] 2020-09-25 16:31
I'm puzzled why he communicated with you but not with me. Show some sign of life.

I think too strict opsec that locks you out of your system is your own responsibility, make backups, and backups of backups.
I would assume that somebody handling this amount of funds surely knows what they are doing. At least they should, and if things go wrong, the party they are trading with should not become victim of their (flawed or overly strict) security model.

On 26th of august I informed him in this trade chat that i've sent the payment for MZEFILM but not this one yet, and that i would like to resolve the issue with TradeID 49320 first. No response.

**Comment by Bisq-knight** [comment] 2020-09-26 15:06
> I think too strict opsec that locks you out of your system is your own responsibility, make backups, and backups of backups.
> I would assume that somebody handling this amount of funds surely knows what they are doing. At least they should, and if things go wrong, the party they are trading with should not become victim of their (flawed or overly strict) security model.


Trust me, Bitcoin will have it's own category in the Darwin Awards

**Comment by Bisq-knight** [comment] 2020-11-02 17:46
Closing this as it was solved in the other proposal #502

**Closed by Bisq-knight** 2020-11-02 17:46 UTC
